version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=telegram_posts
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./telePosting
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB_NAME=telegram_posts
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./telePostFrontend/vite-project
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
